#!/bin/bash

#docker run --rm --env=REGISTRY_STORAGE_DELETE_ENABLED=True --name=registry -env=REGISTRY_HTTP_ADDR=:5000 -p 5000:5000 registry:2.7.1

docker run --rm --env=REGISTRY_STORAGE_DELETE_ENABLED=True --name=registry -env=REGISTRY_HTTP_ADDR=:5000 -p 5000:5000 2c917776ef8e
