#!/bin/bash

docker build . -t logs/generator
docker rm -f logs_generator || echo "no container running yet"
docker run -d --name logs_generator --log-driver json-file --log-opt max-size=1m --log-opt max-file=2 logs/generator
