#!/bin/bash

echo "help" | sudo socat stdio run/admin.sock
echo "set server back1/web2 addr 172.18.0.2 port 5001 state ready" | sudo socat stdio run/admin.sock
echo "enable server back1/web2" | sudo socat stdio run/admin.sock
